; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F411RE]
platform = ststm32
board = genericSTM32F411RE
framework = stm32cube
build_flags = -std=gnu++17
build_src_filter = +<*> -<native_main.cpp>

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_type = debug
build_unflags = -Wl, --gc-sections
upload_protocol = custom
upload_command = echo "no upload"
build_src_filter =
    +<actuators/>
    +<core/>
    +<diagnostics/>
    +<sensors/>
    +<ui/>
    +<native_main.cpp>
    -<platform/>
    -<core/main.cpp>

[env:native_csc]
; test-only environment (use: pio test -e native_csc)
; running "pio run -e native_csc" is expected to fail (no program main)
platform = native
build_type = debug
test_framework = unity
test_build_src = true
build_src_filter = 
    +<core/steering/csc.cpp>
    +<core/config.h>
    +<types/globalTypes.h>
